# Generated by Django 2.1 on 2018-08-29 11:38

import auth_backend.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код роли')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование роли')),
                ('permissions', models.ManyToManyField(to='permission.RolePermission', verbose_name='Список разрешений')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'db_table': 'roles',
            },
            bases=(models.Model, auth_backend.user.models.UserMixin),
        ),
    ]
