# Generated by Django 2.1 on 2018-08-31 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('role', '0001_initial'),
        ('organization', '0002_auto_20180831_1246'),
        ('permission', '0002_auto_20180831_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='permission.RolePermission', verbose_name='Список разрешений'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='organizations',
            field=models.ManyToManyField(to='organization.Organization', verbose_name='Список организаций'),
        ),
        migrations.AddField(
            model_name='organizationrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.Role', verbose_name='Ссылка на роль'),
        ),
    ]
