# Generated by Django 2.1.3 on 2018-12-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_auto_20181129_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-id',), 'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
    ]
