# Generated by Django 2.1.3 on 2018-12-17 07:01

from django.db import migrations


def forwards_func(apps, schema_editor):
    Role = apps.get_model('role', 'Role')
    Role.objects.filter(code='administrator', name='Администратор').delete()
    Role.objects.filter(code='guest', name='Гость').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20181217_0701'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
