# Generated by Django 2.1 on 2018-08-31 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20180831_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationrole',
            options={'verbose_name': 'Роль в организации', 'verbose_name_plural': 'Роли на организациях'},
        ),
    ]
