# Generated by Django 2.1 on 2018-08-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Юридический'), (2, 'Фактический')])),
                ('zipcode', models.CharField(default='', max_length=20, verbose_name='Почтовый индекс')),
                ('place', models.CharField(default='', max_length=128, verbose_name='Населенный пункт')),
                ('street', models.CharField(default='', max_length=128, verbose_name='Улица')),
                ('house_num', models.CharField(default='', max_length=20, verbose_name='Дом')),
                ('housing', models.CharField(default='', max_length=20, verbose_name='Корпус')),
                ('flat', models.CharField(default='', max_length=20, verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'addresses',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boss_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель организации'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(default='', max_length=32, verbose_name='Эл.почта'),
        ),
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.CharField(default='', max_length=12, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='license',
            field=models.CharField(default='', max_length=128, verbose_name='Номер лицензии'),
        ),
        migrations.AddField(
            model_name='organization',
            name='okato',
            field=models.CharField(default='', max_length=12, verbose_name='ОКАТО'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.CharField(default='', max_length=128, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_fact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fact_organizations', to='organization.Address', verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_jur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jur_organizations', to='organization.Address', verbose_name='Юридический адрес'),
        ),
    ]
