# Generated by Django 2.1 on 2018-08-29 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180829_1724'),
        ('organization', '0002_auto_20180829_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fact_organizations', to='address.Address', verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_jur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jur_organizations', to='address.Address', verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boss_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Эл.почта'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='full_name',
            field=models.TextField(blank=True, verbose_name='Полное наименование организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='license',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Номер лицензии'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='okato',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ОКАТО'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='site',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Сайт'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
