# Generated by Django 2.1.1 on 2018-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения записи')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код разрешения')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование разрешения')),
            ],
            options={
                'verbose_name': 'Разрешение роли',
                'verbose_name_plural': 'Разрешения ролей',
                'db_table': 'permissions',
            },
        ),
    ]
