# Generated by Django 2.1 on 2018-08-29 11:38

import auth_backend.user.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код разрешения')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование разрешения')),
            ],
            options={
                'verbose_name': 'Базовое разрешение роли',
                'verbose_name_plural': 'Базовые разрешения ролей',
                'db_table': 'meta_permissions',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код разрешения')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование разрешения')),
                ('meta_permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.MetaPermission', verbose_name='Ссылка на базовое разрешение')),
                ('organizations', models.ManyToManyField(blank=True, to='organization.Organization', verbose_name='Список организаций')),
            ],
            options={
                'verbose_name': 'Разрешение роли',
                'verbose_name_plural': 'Разрешения ролей',
                'db_table': 'permissions',
            },
            bases=(models.Model, auth_backend.user.models.UserMixin),
        ),
    ]
