# Generated by Django 2.1 on 2018-09-04 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='meta_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permission.MetaPermission', verbose_name='Ссылка на базовое разрешение'),
        ),
    ]
