# Generated by Django 2.1.3 on 2018-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='changed_at',
            new_name='updated_at',
        ),
    ]
