# Generated by Django 2.1 on 2018-08-31 09:46

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('address', '0001_initial'),
        ('role', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Эл.почта')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперадмин')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('iname', models.CharField(blank=True, default='', max_length=30, verbose_name='Имя')),
                ('fname', models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия')),
                ('oname', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('photo', models.FileField(null=True, upload_to='avatars', verbose_name='Фото')),
                ('admission_date', models.DateField(null=True, verbose_name='Дата приема на работу')),
                ('phone', models.CharField(blank=True, default='', max_length=128, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='address.Address', verbose_name='Адрес')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('organizations', models.ManyToManyField(to='organization.Organization', verbose_name='Список организаций')),
                ('roles', models.ManyToManyField(to='role.OrganizationRole', verbose_name='Роли пользователя')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь системы',
                'verbose_name_plural': 'Пользователи системы',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
